### ISSUE TITLE
Disable Editing Previous Answers

### ISSUE THREAD

**Issue by ismk** [space10-community/conversational-form#144]
Hello! 
Is there any way we could disable editing previous answers ?

**Comment by felixnielsen** [comment]
hi @ismk you can add a styling rule from your side and overwrite standard behaviour:

```css
.conversational-form cf-chat-response.user.can-edit{
    pointer-events: none;
}
```
