### ISSUE TITLE
Prevent user from editing previous answers

### ISSUE THREAD

**Issue by karthikradhakrishnan96** [space10-community/conversational-form#160]
Hey. I'd like to prevent the user from clicking on his previous answers and changing them. Is there an option to do it?

**Comment by felixnielsen** [comment]
hi @karthikradhakrishnan96 — you can overwrite this behaviour through css.

```css
cf-chat-response.user.can-edit{
  pointer-events: none;
}
````
